version: '3.7'

services:

  app:
    image: fabianbello/app_meetflow:v54
    container_name: app_meetflow
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 80:3000
      - 82:82
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-meetings:
    image: fabianbello/microservice-meetings:v36
    container_name: microservice-meetings
    build:
      context: ./microservice-meetings
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-users:
    image: fabianbello/microservice-users:v25
    container_name: microservice-users
    build:
      context: ./microservice-users
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-premeetings:
    image: fabianbello/microservice-premeetings:v21
    container_name: microservice-premeetings
    build:
      context: ./microservice-premeetings
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-postmeetings:
    image: fabianbello/microservice-postmeetings:v21
    container_name: microservice-postmeetings
    build:
      context: ./microservice-postmeetings
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-meetingminutes:
    image: fabianbello/microservice-meetingminutes:v25
    container_name: microservice-meetingminutes
    build:
      context: ./microservice-meetingminutes
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-notifications:
    image: fabianbello/microservice-notifications:v36
    container_name: microservice-notifications
    build:
      context: ./microservice-notifications
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-inmeetings:
    image: fabianbello/microservice-inmeetings:v21
    container_name: microservice-inmeetings
    build:
      context: ./microservice-inmeetings
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-elements:
    image: fabianbello/microservice-elements:v32
    container_name: microservice-elements
    build:
      context: ./microservice-elements
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow
  
  microservice-projects:
    image: fabianbello/microservice-projects:v21
    container_name: microservice-projects
    build:
      context: ./microservice-projects
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-reminders:
    image: fabianbello/microservice-reminders:v22
    container_name: microservice-reminders
    build:
      context: ./microservice-reminders
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-tasks:
    image: fabianbello/microservice-tasks:v21
    container_name: microservice-tasks
    build:
      context: ./microservice-tasks
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-kanban:
    image: fabianbello/microservice-kanban:v21
    container_name: microservice-kanban
    build:
      context: ./microservice-kanban
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rmq
    expose:
      - 5672
      - 15672
    restart: always
    networks:
      - ms_meetflow

  mysql:
    image: mysql:latest
    container_name: mysql-microservice-users
    volumes:
      - ./sql-data/db:/var/lib/mysql22
    ports:
      - 3306:3306
    hostname: 'hostdbusers'
    environment:
      MYSQL_DATABASE: 'dbusers'
      MYSQL_USER: 'fabian'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    networks:
      - ms_meetflow

networks:
  ms_meetflow: