version: '3.7'

services:
  app:
    image: app_meetflow:v4
    container_name: app_meetflow
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 80:3000
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow
  
  microservice-projects:
    image: microservice-projects:v4
    container_name: microservice-projects
    build:
      context: ./microservice-projects
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-guests:
    image: microservice-guests:v4
    container_name: microservice-guests
    build:
      context: ./microservice-guests
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-users:
    image: microservice-users:v5
    container_name: microservice-users
    build:
      context: ./microservice-users
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-meetings:
    image: microservice-meetings:v4
    container_name: microservice-meetings
    build:
      context: ./microservice-meetings
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rmq
    expose:
      - 5672
      - 15672
    restart: always
    networks:
      - ms_meetflow

  mysql:
    image: mysql:latest
    container_name: mysql-microservice-users
    volumes:
      - ./sql-data/db:/var/lib/mysql
    ports:
      - 3306:3306
    hostname: 'hostdbusers'
    environment:
      MYSQL_DATABASE: 'dbusers'
      MYSQL_USER: 'fabian'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    networks:
      - ms_meetflow

networks:
  ms_meetflow: